name: Semgrep SAST Analysis

on:
  push:
    branches: [master, main]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [master, main]
    paths-ignore:
      - '.github/**'

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        continue-on-error: true
        run: >
          semgrep scan
          --config p/default
          --config p/security-audit
          --config p/owasp-top-ten
          --config p/cwe-top-25
          --config p/secrets
          --config p/ci
          --config p/0xdea
          --severity ERROR
          --severity WARNING
          --exclude-rule 0xdea.c.interesting-api-calls.raptor-interesting-api-calls
          --exclude-rule 0xdea.c.argv-envp-access.raptor-argv-envp-access
          --exclude-rule 0xdea.c.typos.raptor-typos
          --exclude-rule 0xdea.c.mismatched-memory-management.raptor-mismatched-memory-management
          --exclude-rule 0xdea.c.pointer-subtraction.raptor-pointer-subtraction
          --exclude-rule 0xdea.c.missing-return.raptor-missing-return
          --exclude-rule 0xdea.c.missing-default-in-switch.raptor-missing-default-in-switch
          --exclude-rule 0xdea.c.missing-break-in-switch.raptor-missing-break-in-switch
          --exclude-rule 0xdea.c.write-into-stack-buffer.raptor-write-into-stack-buffer
          --exclude-rule 0xdea.c.off-by-one.raptor-off-by-one
          --exclude-rule 0xdea.c.insecure-api-strcpy-strcat.raptor-insecure-api-strcpy-strcat
          --exclude-rule 0xdea.c.unterminated-string-strncpy.raptor-unterminated-string-strncpy
          --exclude .github/workflows
          --sarif --output=semgrep-results.sarif .

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep-results.sarif
          category: semgrep
